### ISSUE TITLE
distance transform

### ISSUE THREAD

**Issue by CNGaoWenbo** [leabogensperger/generative-segmentation-sdf#1]
Hi, could you indicate how to compute the signed distance function from the segmentation ground truth? and a do you need to normalize it into range (-1 1)? thanks a lot

**Comment by leabogensperger** [comment]
I added a toy example that you can  find in preprocess_data/precompute_sdf.ipynb. Some data sets have the contours in the ground truth labels, if this is not the case, you can extract them yourself. However, note that this has to be handled more carefully if you have overlapping/touching objects. 

The SDF masks are normalized to [-1,1]. In the code, I experimented with scaling them to a certain max_value such that they are in [-max_value,max_value] - but I would advise you to just leave them in [-1,1] and adapt \sigma_min if necessary.

**Comment by CNGaoWenbo** [comment]
Great! Thank you for your kind answer. much appreciate it.
